import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../globals.css";
import { Providers } from "../providers";
import Header from "@/components/shared/Header";
import Sidebar from "@/components/shared/Sidebar";
import AuthProvider from "@/hooks/AuthProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "KSB Exams Attendance | Admin",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <AuthProvider>
      <html lang="en">
        <body className={inter.className}>
          <Providers>
            <Header />
            <main className="min-[845px]:flex">
              <Sidebar />
              <section className="main-container">{children}</section>
            </main>
          </Providers>
        </body>
      </html>
    </AuthProvider>
  );
}
